# Generated by Django 4.0.5 on 2022-07-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0003_clothes_delete_clothe'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='qty_parcel',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='value_parcel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
