# Generated by Django 4.0.5 on 2022-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0004_clothes_qty_parcel_clothes_value_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='qty_parcel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
