# Generated by Django 4.0.5 on 2022-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0006_clothes_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
    ]
