# Generated by Django 4.0.5 on 2022-07-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0008_clothes_brands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ('-created_at',), 'verbose_name': 'Roupa', 'verbose_name_plural': 'Roupas'},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(max_length=165, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Unisex', 'Unisex')], default='Unisex', max_length=9, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Está publicado'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='length',
            field=models.CharField(max_length=100, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='qty_parcel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizaco em'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='value_parcel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Valor das Parcelas'),
        ),
    ]
