# Generated by Django 4.0.5 on 2022-08-05 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('angel', '0009_alter_category_options_alter_clothes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brands',
            field=models.ManyToManyField(to='brand.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='angel.category', verbose_name='Categoria'),
        ),
    ]
